/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BeyimXapi {
        /**
          * Component stuff
         */
        "backend"?: string;
        "debug"?: boolean;
        "host_url"?: string;
        "name": string;
        "subject": string|undefined;
        "type": 'button'|'view';
        /**
          * X-API stuff
         */
        "verb": string;
        "view_threshold"?: number;
        "view_timeout"?: number;
    }
}
declare global {
    interface HTMLBeyimXapiElement extends Components.BeyimXapi, HTMLStencilElement {
    }
    var HTMLBeyimXapiElement: {
        prototype: HTMLBeyimXapiElement;
        new (): HTMLBeyimXapiElement;
    };
    interface HTMLElementTagNameMap {
        "beyim-xapi": HTMLBeyimXapiElement;
    }
}
declare namespace LocalJSX {
    interface BeyimXapi {
        /**
          * Component stuff
         */
        "backend"?: string;
        "debug"?: boolean;
        "host_url"?: string;
        "name": string;
        "subject": string|undefined;
        "type": 'button'|'view';
        /**
          * X-API stuff
         */
        "verb": string;
        "view_threshold"?: number;
        "view_timeout"?: number;
    }
    interface IntrinsicElements {
        "beyim-xapi": BeyimXapi;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "beyim-xapi": LocalJSX.BeyimXapi & JSXBase.HTMLAttributes<HTMLBeyimXapiElement>;
        }
    }
}
